export const DOODLE_ARTBOARD_INSET = 18;
export const STICKER_ARTBOARD_INSET = 6;

export const DOODLE_ARTBOARD_FRAME = {
  top: DOODLE_ARTBOARD_INSET,
  right: DOODLE_ARTBOARD_INSET,
  bottom: DOODLE_ARTBOARD_INSET,
  left: DOODLE_ARTBOARD_INSET,
} as const;

export const STICKER_ARTBOARD_FRAME = {
  top: STICKER_ARTBOARD_INSET,
  right: STICKER_ARTBOARD_INSET,
  bottom: STICKER_ARTBOARD_INSET,
  left: STICKER_ARTBOARD_INSET,
} as const;
