import { Dimensions, Platform, StyleSheet } from 'react-native';
import { STICKER_ARTBOARD_FRAME } from '../../../constants/doodleLayout';
import { Layout, Radii, Shadows, Sheet, Typography } from '../../../constants/theme';

const { width } = Dimensions.get('window');

export const HORIZONTAL_PADDING = Layout.screenPadding - 8;
export const CARD_SIZE = width - HORIZONTAL_PADDING * 2;
export const TOP_CONTROL_INSET = 24;
export const TOP_CONTROL_HEIGHT = 38;
export const TOP_CONTROL_RADIUS = 19;
export const CARD_CHROME_SAFE_TOP = 30;
export const DECORATE_OPTION_ACTIVE_SCALE = 1;
export const DECORATE_OPTION_CONTENT_SCALE = 1;
export const SHUTTER_OUTER_SIZE = 74;
export const SHUTTER_INNER_SIZE = 58;
export const SIDE_ACTION_SIZE = 46;
export const SHUTTER_SIDE_ACTION_GAP = 24;
export const SHUTTER_SIDE_ACTION_OFFSET =
  SHUTTER_OUTER_SIZE / 2 + SHUTTER_SIDE_ACTION_GAP + SIDE_ACTION_SIZE;
export const PHOTO_DOODLE_DEFAULT_COLOR = '#FFFFFF';
export const PHOTO_CAPTION_MAX_LENGTH = 60;
export const LIVE_PHOTO_RING_STROKE_WIDTH = 4;
export const CAMERA_FOCUS_RING_SIZE = 64;
export const DOCKED_HEADER_CONTENT_OVERLAP = 8;
const SHEET_HORIZONTAL_PADDING =
  Platform.OS === 'ios' ? Sheet.ios.horizontalPadding : Sheet.android.horizontalPadding;

export const styles = StyleSheet.create({
  captureKeyboardAvoiding: {
    width: '100%',
  },
  captureButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  captureToggleIconWrap: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  captureToggleIconLayer: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  snapItem: {
    width,
    justifyContent: 'center',
  },
  captureArea: {
    height: CARD_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  textCard: {
    width: CARD_SIZE,
    height: CARD_SIZE,
    borderRadius: Layout.cardRadius,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    padding: 28,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
    ...(Platform.OS === 'android' ? {} : Shadows.card),
  },
  textCardLightContrast: {
    borderWidth: 1,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
    elevation: 10,
  },
  cardPasteSurface: {
    ...StyleSheet.absoluteFill,
    zIndex: 0,
  },
  textInput: {
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    textAlignVertical: 'center',
    lineHeight: 34,
    paddingTop: 0,
    paddingBottom: 0,
    width: '100%',
    textShadowRadius: 6,
    fontFamily: 'Noto Sans',
    maxHeight: 260,
  },
  cardTextCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    zIndex: 1,
  },
  autoEmojiPopWrap: {
    position: 'absolute',
    top: 56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 4,
    zIndex: 2,
  },
  autoEmojiPopEmoji: {
    fontSize: 18,
    lineHeight: 20,
  },
  inlinePasteStickerWrap: {
    overflow: 'hidden',
    height: TOP_CONTROL_HEIGHT,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  inlinePasteStickerIconButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
  },
  nativeInlinePasteStickerButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
  },
  cardTopOverlay: {
    position: 'absolute',
    top: CARD_CHROME_SAFE_TOP,
    left: 14,
    right: 14,
    gap: 8,
    alignItems: 'center',
    zIndex: 11,
  },
  cardBottomOverlay: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    alignItems: 'center',
    zIndex: 12,
  },
  cardTopOverlayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 8,
  },
  cardTopOverlayRowWrap: {
    flexWrap: 'wrap',
  },
  photoTopToolsBar: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  photoTopToolsRow: {
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  photoTopDetailAction: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  photoDoodleActionsCluster: {
    flexDirection: 'row',
    gap: 8,
  },
  photoDoodleIconButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textCardActionCluster: {
    flexDirection: 'row',
    gap: 8,
  },
  textCardActionButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textCardInlineColorPreview: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  decorateToggleButton: {
    width: 50,
    height: 40,
    paddingHorizontal: 0,
    borderRadius: 20,
  },
  decorateChevronWrap: {
    width: 13,
    height: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  decorateControlsWrap: {
    overflow: 'hidden',
    height: TOP_CONTROL_HEIGHT,
    justifyContent: 'center',
  },
  decorateControlsInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  textCardActionPill: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  captureActionTextPill: {
    width: 'auto',
    minWidth: 58,
    paddingHorizontal: 12,
  },
  captureActionPillLabel: {
    fontSize: 11,
    fontWeight: '700',
  },
  livePhotoTogglePill: {
    width: TOP_CONTROL_HEIGHT,
    minWidth: TOP_CONTROL_HEIGHT,
    paddingHorizontal: 0,
    justifyContent: 'center',
  },
  doodleColorPalette: {
    width: 96,
    overflow: 'hidden',
  },
  doodleColorPaletteScroll: {
    flexGrow: 0,
  },
  doodleColorPaletteContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingRight: 4,
  },
  doodleColorButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doodleColorSwatch: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: StyleSheet.hairlineWidth,
  },
  doodleCanvasLayer: {
    ...StyleSheet.absoluteFill,
    ...STICKER_ARTBOARD_FRAME,
    zIndex: 2,
  },
  textStickerCanvasLayer: {
    ...StyleSheet.absoluteFill,
    ...STICKER_ARTBOARD_FRAME,
    zIndex: 0,
  },
  cardRestaurantPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 42,
    paddingHorizontal: 10,
    paddingVertical: 0,
    borderRadius: Radii.pill,
    borderWidth: StyleSheet.hairlineWidth,
    width: '100%',
    overflow: 'hidden',
    position: 'relative',
    zIndex: 3,
  },
  cardRestaurantPillOverlay: {
    width: 'auto',
    maxWidth: CARD_SIZE - 140,
    minWidth: 210,
    alignSelf: 'center',
    paddingHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  cardRestaurantPillBelow: {
    marginTop: 0,
  },
  captureMetaComposite: {
    width: '100%',
    maxWidth: 344,
    alignSelf: 'center',
    paddingHorizontal: 12,
    gap: 0,
  },
  captureMetaStack: {
    width: '100%',
    alignItems: 'center',
    gap: 8,
  },
  captureMetaInputWrap: {
    flex: 1,
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  captureMetaActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  cardRestaurantInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 17,
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: 48,
  },
  cardRestaurantInputCompact: {
    paddingRight: 0,
  },
  captureMetaDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
    marginHorizontal: 5,
    opacity: 0.45,
  },
  captureInlineRadiusButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  captureInlineColorButton: {
    width: 31,
    height: 31,
    borderRadius: 15.5,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  captureInlineColorPreview: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  cameraContainer: {
    width: CARD_SIZE,
    height: CARD_SIZE,
    borderRadius: Layout.cardRadius,
    borderCurve: 'continuous',
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    ...(Platform.OS === 'android' ? {} : Shadows.card),
    backgroundColor: '#000',
  },
  cameraOverlayButton: {
    borderWidth: StyleSheet.hairlineWidth,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    zIndex: 10,
  },
  cameraPreview: {
    ...StyleSheet.absoluteFill,
  },
  cameraGestureLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  cameraFocusRing: {
    position: 'absolute',
    width: CAMERA_FOCUS_RING_SIZE,
    height: CAMERA_FOCUS_RING_SIZE,
    borderRadius: CAMERA_FOCUS_RING_SIZE / 2,
    borderWidth: 2,
    backgroundColor: 'transparent',
    zIndex: 6,
  },
  cameraTransitionOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: '#000000',
    zIndex: 1,
  },
  cameraSurfaceStack: {
    width: CARD_SIZE,
    height: CARD_SIZE,
    position: 'relative',
  },
  cameraSurfaceLayer: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraSurfaceTopLayer: {
    zIndex: 1,
  },
  captureTransitionCover: {
    ...StyleSheet.absoluteFill,
    backgroundColor: '#000000',
    zIndex: 50,
  },
  cameraLiveProgressOverlay: {
    ...StyleSheet.absoluteFill,
    zIndex: 3,
  },
  cameraLiveProgressCanvas: {
    width: '100%',
    height: '100%',
  },
  cameraZoomBadge: {
    position: 'absolute',
    top: CARD_CHROME_SAFE_TOP,
    right: 16,
    minWidth: 58,
    minHeight: TOP_CONTROL_HEIGHT,
    paddingHorizontal: 12,
    borderRadius: TOP_CONTROL_RADIUS,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(28,28,30,0.52)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.18)',
    zIndex: 10,
  },
  cameraZoomBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Noto Sans',
  },
  cameraUnavailableState: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    gap: 12,
  },
  cameraPermissionOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    gap: 12,
  },
  cameraUnavailableTitle: {
    ...Typography.body,
    textAlign: 'center',
    fontWeight: '700',
  },
  cameraUnavailableHint: {
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '500',
    fontFamily: 'Noto Sans',
    lineHeight: 18,
  },
  cameraRetryButton: {
    minWidth: 150,
    marginTop: 4,
  },
  libraryBtn: {
    position: 'absolute',
    top: TOP_CONTROL_INSET,
    left: 16,
    minHeight: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    zIndex: 10,
  },
  libraryBtnText: {
    fontWeight: '600',
    fontSize: 13,
  },
  permissionText: {
    ...Typography.body,
    textAlign: 'center',
  },
  permissionButton: {
    marginTop: 16,
    width: '100%',
  },
  belowCardSection: {
    paddingHorizontal: HORIZONTAL_PADDING + 4,
    paddingTop: 14,
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: 162,
    gap: 10,
  },
  belowCardMetaRow: {
    width: '100%',
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  photoCaptionIcon: {
    marginTop: 0,
  },
  photoCaptionOverlayField: {
    width: '84%',
    minHeight: 38,
    borderRadius: 19,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  photoCaptionOverlayInput: {
    flex: 1,
    height: 20,
    fontSize: 13.5,
    lineHeight: 18,
    fontWeight: '600',
    fontFamily: 'Noto Sans',
    paddingVertical: 0,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  photoCaptionClearButton: {
    marginLeft: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textBottomToolsWrap: {
    width: '100%',
    alignItems: 'center',
    gap: 8,
  },
  captureActionBarWrap: {
    width: '100%',
    alignItems: 'center',
  },
  textBottomToolsBar: {
    alignSelf: 'center',
    minHeight: 46,
    borderRadius: Radii.pill,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  textBottomToolsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    flexWrap: 'nowrap',
    minHeight: TOP_CONTROL_HEIGHT,
    gap: 8,
  },
  textBottomToolsButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textBottomToolsAction: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textBottomDetailAction: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  captureStandaloneRadiusButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  captureStandaloneRadiusButtonContent: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraStatusText: {
    ...Typography.pill,
    textAlign: 'center',
  },
  cameraStatusSlot: {
    minHeight: 20,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  cameraInstructionText: {
    ...Typography.pill,
    textAlign: 'center',
  },
  cameraActionHintWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  cameraActionHintText: {
    ...Typography.pill,
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
    fontWeight: '700',
  },
  cameraControlsWrap: {
    width: '100%',
    position: 'relative',
    alignItems: 'center',
  },
  cameraMetaSlot: {
    width: '100%',
    minHeight: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraMetaHintLayer: {
    position: 'absolute',
    alignSelf: 'center',
  },
  cameraMetaButtonLayer: {
    position: 'absolute',
    alignSelf: 'center',
  },
  cameraHintPill: {
    minHeight: 34,
    maxWidth: '100%',
    borderRadius: Radii.pill,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    justifyContent: 'center',
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  cameraHintContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  cameraHintText: {
    ...Typography.pill,
    fontSize: 13,
    lineHeight: 16,
    textAlign: 'center',
  },
  cameraHintSeparator: {
    fontSize: 12,
    lineHeight: 16,
  },
  cameraHintAccentText: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '600',
    fontFamily: 'Noto Sans',
  },
  belowCardShutterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 92,
    paddingTop: 12,
    paddingBottom: 14,
    width: '100%',
    position: 'relative',
  },
  belowCardCapturedPhotoActions: {
    minHeight: 92,
    paddingTop: 12,
    paddingBottom: 14,
  },
  liveCameraShutterRow: {
    minHeight: 92,
    paddingTop: 12,
    paddingBottom: 14,
  },
  photoFilterTray: {
    maxWidth: '100%',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 5,
    paddingVertical: 4,
    overflow: 'hidden',
  },
  photoFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  photoFilterButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 19,
    borderWidth: 2,
    padding: 1,
  },
  photoFilterPreviewClip: {
    width: 34,
    height: 34,
    borderRadius: 17,
    overflow: 'hidden',
  },
  photoFilterPreviewCanvas: {
    width: '100%',
    height: '100%',
  },
  belowCardLeadingAction: {
    position: 'absolute',
    left: '50%',
    marginLeft: -SHUTTER_SIDE_ACTION_OFFSET,
  },
  belowCardTrailingAction: {
    position: 'absolute',
    left: '50%',
    marginLeft: SHUTTER_OUTER_SIZE / 2 + SHUTTER_SIDE_ACTION_GAP,
  },
  belowCardSideActionSpacer: {
    width: SIDE_ACTION_SIZE,
    height: SIDE_ACTION_SIZE,
  },
  secondaryActionButton: {
    width: SIDE_ACTION_SIZE,
    height: SIDE_ACTION_SIZE,
    borderRadius: SIDE_ACTION_SIZE / 2,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryActionButtonContent: {
    width: '100%',
    height: '100%',
  },
  shutterOuter: {
    width: SHUTTER_OUTER_SIZE,
    height: SHUTTER_OUTER_SIZE,
    borderRadius: SHUTTER_OUTER_SIZE / 2,
    borderWidth: 4,
    borderColor: 'rgba(150,150,150,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'visible',
  },
  shutterCaptureHalo: {
    position: 'absolute',
    width: SHUTTER_OUTER_SIZE + 18,
    height: SHUTTER_OUTER_SIZE + 18,
    borderRadius: (SHUTTER_OUTER_SIZE + 18) / 2,
  },
  shutterInner: {
    width: SHUTTER_INNER_SIZE,
    height: SHUTTER_INNER_SIZE,
    borderRadius: SHUTTER_INNER_SIZE / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveInner: {
    transform: [{ scale: 1 }],
    overflow: 'hidden',
  },
  saveHalo: {
    ...StyleSheet.absoluteFill,
    borderRadius: SHUTTER_INNER_SIZE / 2,
  },
  shutterInnerCountText: {
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '800',
  },
  footerSlot: {
    width: '100%',
    paddingTop: 2,
  },
  noteColorSheet: {
    gap: 12,
    paddingBottom: Sheet.android.bottomPadding + Sheet.android.comfortBottomPadding,
  },
  noteColorPreviewHint: {
    marginTop: 12,
    textAlign: 'left',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  radiusSheet: {
    gap: 12,
    paddingBottom: Sheet.android.bottomPadding + Sheet.android.comfortBottomPadding,
  },
  radiusSheetRow: {
    minHeight: 60,
    paddingHorizontal: Sheet.android.horizontalPadding,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  radiusSheetRowPressed: {
    opacity: 0.9,
  },
  radiusSheetLabel: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Noto Sans',
  },
  stickerActionsSheet: {
    paddingTop: 6,
  },
  stickerActionsSheetHeader: {
    paddingHorizontal: SHEET_HORIZONTAL_PADDING,
    paddingBottom: 10,
  },
  stickerActionsSheetTitle: {
    ...Typography.screenTitle,
    textAlign: 'left',
  },
  stickerActionsSheetList: {
    paddingBottom: 0,
  },
  stickerActionsSheetFooter: {
    marginTop: 0,
  },
  stickerActionsSheetRow: {
    minHeight: 68,
    paddingHorizontal: SHEET_HORIZONTAL_PADDING,
    justifyContent: 'center',
  },
  stickerActionsSheetRowPressed: {
    opacity: 0.82,
  },
  stickerActionsSheetRowContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  stickerActionsSheetIconBadge: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stickerActionsSheetLabel: {
    ...Typography.body,
    flex: 1,
    fontWeight: '600',
  },
  stickerActionsSheetDivider: {
    height: StyleSheet.hairlineWidth,
    marginLeft: SHEET_HORIZONTAL_PADDING + 54,
  },
  radiusSheetDivider: {
    height: StyleSheet.hairlineWidth,
    marginLeft: Sheet.android.horizontalPadding,
  },
});
