import { Dimensions, Platform, StyleSheet } from 'react-native';
import { STICKER_ARTBOARD_FRAME } from '../../../constants/doodleLayout';
import { Layout, Radii, Shadows, Sheet, Typography } from '../../../constants/theme';

const { width } = Dimensions.get('window');

export const HORIZONTAL_PADDING = Layout.screenPadding - 8;
export const CARD_SIZE = width - HORIZONTAL_PADDING * 2;
export const TOP_CONTROL_INSET = 24;
export const TOP_CONTROL_HEIGHT = 38;
export const TOP_CONTROL_RADIUS = 19;
export const CARD_CONTENT_PADDING = 28;
export const CARD_CHROME_SAFE_TOP = 30;
export const AUTO_EMOJI_POP_TOP = 56;
export const DECORATE_OPTION_ACTIVE_SCALE = 1;
export const DECORATE_OPTION_CONTENT_SCALE = 1;
export const SHUTTER_OUTER_SIZE = 74;
export const SHUTTER_INNER_SIZE = 58;
export const SIDE_ACTION_SIZE = 46;
export const DOODLE_COLOR_BUTTON_SIZE = 32;
export const SHUTTER_SIDE_ACTION_GAP = 32;
export const SHUTTER_SIDE_ACTION_OFFSET =
  SHUTTER_OUTER_SIZE / 2 + SHUTTER_SIDE_ACTION_GAP + SIDE_ACTION_SIZE;
export const PHOTO_DOODLE_DEFAULT_COLOR = '#FFFFFF';
export const PHOTO_CAPTION_MAX_LENGTH = 60;
export const LIVE_PHOTO_RING_STROKE_WIDTH = 4;
export const CAMERA_FOCUS_RING_SIZE = 64;
export const DOCKED_HEADER_CONTENT_OVERLAP = 8;
export const CAMERA_ZOOM_BADGE_BACKGROUND = 'rgba(28,28,30,0.52)';
const SHEET_HORIZONTAL_PADDING =
  Platform.OS === 'ios' ? Sheet.ios.horizontalPadding : Sheet.android.horizontalPadding;

export const styles = StyleSheet.create({
  captureKeyboardAvoiding: {
    width: '100%',
  },
  captureButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  captureToggleIconWrap: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  captureToggleIconLayer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  snapItem: {
    width,
    justifyContent: 'center',
  },
  captureArea: {
    height: CARD_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  textCardShadow: {
    width: CARD_SIZE,
    height: CARD_SIZE,
    borderRadius: Layout.cardRadius,
    borderCurve: 'continuous',
    ...(Platform.OS === 'android' ? {} : Shadows.card),
  },
  textCardShadowLightContrast: {
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
    elevation: 10,
  },
  textCard: {
    flex: 1,
    borderRadius: Layout.cardRadius,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    padding: CARD_CONTENT_PADDING,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  textCardLightContrast: {
    borderWidth: 1,
  },
  cardPasteSurface: {
    ...StyleSheet.absoluteFill,
    zIndex: 0,
  },
  textInput: {
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    textAlignVertical: 'center',
    lineHeight: 34,
    paddingTop: 0,
    paddingBottom: 0,
    width: '100%',
    textShadowRadius: 6,
    fontFamily: 'Noto Sans',
    maxHeight: 260,
  },
  cardTextCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    zIndex: 1,
  },
  autoEmojiPopWrap: {
    position: 'absolute',
    top: AUTO_EMOJI_POP_TOP,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 4,
    zIndex: 2,
  },
  autoEmojiPopEmoji: {
    fontSize: 18,
    lineHeight: 20,
  },
  inlinePasteStickerWrap: {
    overflow: 'hidden',
    height: TOP_CONTROL_HEIGHT,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  inlinePasteStickerIconButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
  },
  nativeInlinePasteStickerButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
  },
  cardBottomOverlay: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    alignItems: 'center',
    zIndex: 12,
  },
  photoDoodleActionsCluster: {
    flexDirection: 'row',
    gap: 8,
  },
  photoDoodleIconButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textCardActionCluster: {
    flexDirection: 'row',
    gap: 8,
  },
  textCardActionButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textCardInlineColorPreview: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  decorateToggleButton: {
    width: 50,
    height: 40,
    paddingHorizontal: 0,
    borderRadius: 20,
  },
  decorateChevronWrap: {
    width: 13,
    height: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  decorateControlsWrap: {
    overflow: 'hidden',
    height: TOP_CONTROL_HEIGHT,
    justifyContent: 'center',
  },
  decorateControlsInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  textCardActionPill: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doodleColorPalette: {
    width: 96,
    overflow: 'hidden',
  },
  doodleColorPaletteScroll: {
    flexGrow: 0,
  },
  doodleColorPaletteContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingRight: 4,
  },
  doodleColorButton: {
    width: DOODLE_COLOR_BUTTON_SIZE,
    height: DOODLE_COLOR_BUTTON_SIZE,
    borderRadius: DOODLE_COLOR_BUTTON_SIZE / 2,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doodleColorSwatch: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: StyleSheet.hairlineWidth,
  },
  doodleCanvasLayer: {
    ...StyleSheet.absoluteFill,
    ...STICKER_ARTBOARD_FRAME,
    zIndex: 2,
  },
  textStickerCanvasLayer: {
    ...StyleSheet.absoluteFill,
    ...STICKER_ARTBOARD_FRAME,
    zIndex: 0,
  },
  cameraContainer: {
    width: CARD_SIZE,
    height: CARD_SIZE,
    borderRadius: Layout.cardRadius,
    borderCurve: 'continuous',
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    ...(Platform.OS === 'android' ? {} : Shadows.card),
    backgroundColor: '#000',
  },
  cameraOverlayButton: {
    borderWidth: StyleSheet.hairlineWidth,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    zIndex: 10,
  },
  cameraPreview: {
    ...StyleSheet.absoluteFill,
  },
  cameraGestureLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  cameraFocusRing: {
    position: 'absolute',
    width: CAMERA_FOCUS_RING_SIZE,
    height: CAMERA_FOCUS_RING_SIZE,
    borderRadius: CAMERA_FOCUS_RING_SIZE / 2,
    borderWidth: 2,
    backgroundColor: 'transparent',
    zIndex: 6,
  },
  cameraTransitionOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: '#000000',
    zIndex: 1,
  },
  cameraSurfaceStack: {
    width: CARD_SIZE,
    height: CARD_SIZE,
    position: 'relative',
  },
  cameraSurfaceLayer: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraSurfaceTopLayer: {
    zIndex: 1,
  },
  captureTransitionCover: {
    ...StyleSheet.absoluteFill,
    backgroundColor: '#000000',
    zIndex: 50,
  },
  cameraLiveProgressOverlay: {
    ...StyleSheet.absoluteFill,
    zIndex: 3,
  },
  cameraLiveProgressCanvas: {
    width: '100%',
    height: '100%',
  },
  cameraZoomBadge: {
    position: 'absolute',
    top: CARD_CHROME_SAFE_TOP,
    right: 16,
    minWidth: 58,
    minHeight: TOP_CONTROL_HEIGHT,
    paddingHorizontal: 12,
    borderRadius: TOP_CONTROL_RADIUS,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CAMERA_ZOOM_BADGE_BACKGROUND,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.18)',
    zIndex: 10,
  },
  cameraZoomBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Noto Sans',
  },
  cameraUnavailableState: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    gap: 12,
  },
  cameraPermissionOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    gap: 12,
  },
  cameraUnavailableTitle: {
    ...Typography.body,
    textAlign: 'center',
    fontWeight: '700',
  },
  cameraUnavailableHint: {
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '500',
    fontFamily: 'Noto Sans',
    lineHeight: 18,
  },
  cameraRetryButton: {
    minWidth: 150,
    marginTop: 4,
  },
  libraryBtn: {
    position: 'absolute',
    top: TOP_CONTROL_INSET,
    left: 16,
    minHeight: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    zIndex: 10,
  },
  libraryBtnText: {
    fontWeight: '600',
    fontSize: 13,
  },
  permissionText: {
    ...Typography.body,
    textAlign: 'center',
  },
  permissionButton: {
    marginTop: 16,
    width: '100%',
  },
  belowCardSection: {
    paddingHorizontal: HORIZONTAL_PADDING + 4,
    paddingTop: 14,
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: 162,
    gap: 10,
  },
  belowCardMetaRow: {
    width: '100%',
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  belowCardToolbarLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoCaptionIcon: {
    marginTop: 0,
  },
  photoCaptionOverlayField: {
    width: '84%',
    minHeight: 38,
    borderRadius: 19,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  photoCaptionOverlayInput: {
    flex: 1,
    height: 20,
    fontSize: 13.5,
    lineHeight: 18,
    fontWeight: '600',
    fontFamily: 'Noto Sans',
    paddingVertical: 0,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  photoCaptionClearButton: {
    marginLeft: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textBottomToolsWrap: {
    width: '100%',
    alignItems: 'center',
    gap: 8,
  },
  captureActionBarWrap: {
    width: '100%',
    alignItems: 'center',
  },
  liveCameraActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    gap: 6,
  },
  liveCameraFilterRail: {
    flexGrow: 0,
    flexShrink: 0,
  },
  liveCameraActionDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
    marginVertical: 6,
    opacity: 0.9,
  },
  liveCameraImportButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  actionStripIconButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    flexShrink: 0,
  },
  liveFilterScroll: {
    flexGrow: 0,
    flexShrink: 0,
    alignSelf: 'flex-start',
  },
  liveFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingRight: 2,
  },
  liveFilterOption: {
    minHeight: 32,
    minWidth: 32,
    paddingHorizontal: 0,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveFilterSwatch: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: StyleSheet.hairlineWidth,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveFilterSwatchAccent: {
    width: 8,
    height: 8,
    borderRadius: 4,
    opacity: 0.94,
  },
  liveFilterLockBadge: {
    position: 'absolute',
    right: -4,
    bottom: -4,
    width: 11,
    height: 11,
    borderRadius: 5.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textBottomToolsBar: {
    alignSelf: 'center',
    minHeight: 46,
    borderRadius: Radii.pill,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  textBottomToolsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    flexWrap: 'nowrap',
    minHeight: TOP_CONTROL_HEIGHT,
    gap: 8,
  },
  textBottomToolsButton: {
    width: TOP_CONTROL_HEIGHT,
    height: TOP_CONTROL_HEIGHT,
    borderRadius: TOP_CONTROL_RADIUS,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textBottomToolsAction: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textBottomDetailAction: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  captureStandaloneRadiusButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  captureStandaloneRadiusButtonContent: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  captureQuotaHintText: {
    marginTop: 8,
    maxWidth: '88%',
    opacity: 0.84,
  },
  cameraActionHintWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 6,
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  cameraActionHintText: {
    ...Typography.pill,
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
    fontWeight: '700',
  },
  cameraControlsWrap: {
    width: '100%',
    position: 'relative',
    alignItems: 'center',
  },
  belowCardShutterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 92,
    paddingTop: 12,
    paddingBottom: 14,
    width: '100%',
    position: 'relative',
  },
  belowCardCapturedPhotoActions: {
    minHeight: 92,
    paddingTop: 12,
    paddingBottom: 14,
  },
  liveCameraShutterRow: {
    minHeight: 92,
    paddingTop: 12,
    paddingBottom: 14,
  },
  belowCardLeadingAction: {
    position: 'absolute',
    left: '50%',
    marginLeft: -SHUTTER_SIDE_ACTION_OFFSET,
  },
  belowCardTrailingAction: {
    position: 'absolute',
    left: '50%',
    marginLeft: SHUTTER_OUTER_SIZE / 2 + SHUTTER_SIDE_ACTION_GAP,
  },
  belowCardSideActionSpacer: {
    width: SIDE_ACTION_SIZE,
    height: SIDE_ACTION_SIZE,
  },
  secondaryActionButton: {
    width: SIDE_ACTION_SIZE,
    height: SIDE_ACTION_SIZE,
    borderRadius: SIDE_ACTION_SIZE / 2,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryActionButtonContent: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  shutterOuter: {
    width: SHUTTER_OUTER_SIZE,
    height: SHUTTER_OUTER_SIZE,
    borderRadius: SHUTTER_OUTER_SIZE / 2,
    borderWidth: 4,
    borderColor: 'rgba(150,150,150,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'visible',
  },
  shutterCaptureHalo: {
    position: 'absolute',
    width: SHUTTER_OUTER_SIZE + 18,
    height: SHUTTER_OUTER_SIZE + 18,
    borderRadius: (SHUTTER_OUTER_SIZE + 18) / 2,
  },
  shutterInner: {
    width: SHUTTER_INNER_SIZE,
    height: SHUTTER_INNER_SIZE,
    borderRadius: SHUTTER_INNER_SIZE / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveInner: {
    transform: [{ scale: 1 }],
    overflow: 'hidden',
  },
  saveHalo: {
    ...StyleSheet.absoluteFill,
    borderRadius: SHUTTER_INNER_SIZE / 2,
  },
  shutterInnerCountText: {
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '800',
  },
  shutterInnerCompactText: {
    color: '#FFFFFF',
    fontSize: 11,
    lineHeight: 12,
    fontWeight: '800',
    fontFamily: 'Noto Sans',
    textAlign: 'center',
    maxWidth: '80%',
  },
  shutterInnerQuotaWrap: {
    width: '82%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
  },
  shutterInnerQuotaCountText: {
    color: '#FFFFFF',
    fontSize: 20,
    lineHeight: 22,
    fontWeight: '800',
    fontFamily: 'Noto Sans',
    textAlign: 'center',
  },
  shutterInnerQuotaCaptionText: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: 8,
    lineHeight: 9,
    fontWeight: '800',
    fontFamily: 'Noto Sans',
    letterSpacing: 0.3,
    textAlign: 'center',
    textTransform: 'uppercase',
    maxWidth: '100%',
  },
  footerSlot: {
    width: '100%',
    paddingTop: 2,
  },
  noteColorSheet: {
    gap: 12,
    paddingBottom: Sheet.android.bottomPadding + Sheet.android.comfortBottomPadding,
  },
  noteColorPreviewHint: {
    marginTop: 12,
    textAlign: 'left',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  radiusSheet: {
    gap: 12,
    paddingBottom: Sheet.android.bottomPadding + Sheet.android.comfortBottomPadding,
  },
  radiusSheetRow: {
    minHeight: 60,
    paddingHorizontal: Sheet.android.horizontalPadding,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  radiusSheetRowPressed: {
    opacity: 0.9,
  },
  radiusSheetLabel: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Noto Sans',
  },
  stickerActionsSheet: {
    paddingTop: 6,
  },
  stickerActionsSheetHeader: {
    paddingHorizontal: SHEET_HORIZONTAL_PADDING,
    paddingBottom: 10,
  },
  stickerActionsSheetTitle: {
    ...Typography.screenTitle,
    textAlign: 'left',
  },
  stickerActionsSheetList: {
    paddingBottom: 0,
  },
  stickerActionsSheetFooter: {
    marginTop: 0,
  },
  stickerActionsSheetRow: {
    minHeight: 68,
    paddingHorizontal: SHEET_HORIZONTAL_PADDING,
    justifyContent: 'center',
  },
  stickerActionsSheetRowPressed: {
    opacity: 0.82,
  },
  stickerActionsSheetRowContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  stickerActionsSheetIconBadge: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stickerActionsSheetLabel: {
    ...Typography.body,
    flex: 1,
    fontWeight: '600',
  },
  stickerActionsSheetDivider: {
    height: StyleSheet.hairlineWidth,
    marginLeft: SHEET_HORIZONTAL_PADDING + 54,
  },
  radiusSheetDivider: {
    height: StyleSheet.hairlineWidth,
    marginLeft: Sheet.android.horizontalPadding,
  },
});
