begin;

create table if not exists public.social_notification_rate_limit_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('friend_accepted', 'shared_post_created')),
  actor_user_id uuid not null references auth.users(id) on delete cascade,
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  resource_id text,
  created_at timestamptz not null default now()
);

alter table public.social_notification_rate_limit_events enable row level security;

create index if not exists social_notification_rate_limit_events_lookup_idx
  on public.social_notification_rate_limit_events (
    event_type,
    actor_user_id,
    recipient_user_id,
    created_at desc
  );

create unique index if not exists social_notification_rate_limit_events_resource_idx
  on public.social_notification_rate_limit_events (
    event_type,
    actor_user_id,
    recipient_user_id,
    coalesce(resource_id, '')
  );

create or replace function public.reserve_social_notification_delivery(
  event_type_input text,
  actor_user_id_input uuid,
  recipient_user_ids_input uuid[],
  resource_id_input text default null
)
returns table(recipient_user_id uuid)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  normalized_event_type text := btrim(coalesce(event_type_input, ''));
  cooldown_window interval;
  hourly_limit integer;
  daily_limit integer;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Only service-role notification senders can reserve push delivery.'
      using errcode = '42501';
  end if;

  if actor_user_id_input is null then
    raise exception 'Actor user id required.' using errcode = '22023';
  end if;

  if normalized_event_type = 'friend_accepted' then
    cooldown_window := interval '5 minutes';
    hourly_limit := 3;
    daily_limit := 10;
  elsif normalized_event_type = 'shared_post_created' then
    cooldown_window := interval '60 seconds';
    hourly_limit := 12;
    daily_limit := 40;
  else
    raise exception 'Unsupported notification event type: %', event_type_input
      using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtext('social-push:' || actor_user_id_input::text));

  delete from public.social_notification_rate_limit_events
   where created_at < now() - interval '8 days';

  return query
  with requested_recipients as (
    select distinct recipient_id
      from unnest(coalesce(recipient_user_ids_input, array[]::uuid[])) as requested(recipient_id)
     where recipient_id is not null
       and recipient_id is distinct from actor_user_id_input
  ),
  eligible_recipients as (
    select requested_recipients.recipient_id
      from requested_recipients
     where not exists (
       select 1
         from public.social_notification_rate_limit_events recent
        where recent.event_type = normalized_event_type
          and recent.actor_user_id = actor_user_id_input
          and recent.recipient_user_id = requested_recipients.recipient_id
          and recent.created_at >= now() - cooldown_window
     )
       and (
         select count(*)
           from public.social_notification_rate_limit_events hourly
          where hourly.event_type = normalized_event_type
            and hourly.actor_user_id = actor_user_id_input
            and hourly.recipient_user_id = requested_recipients.recipient_id
            and hourly.created_at >= now() - interval '1 hour'
       ) < hourly_limit
       and (
         select count(*)
           from public.social_notification_rate_limit_events daily
          where daily.event_type = normalized_event_type
            and daily.actor_user_id = actor_user_id_input
            and daily.recipient_user_id = requested_recipients.recipient_id
            and daily.created_at >= now() - interval '1 day'
       ) < daily_limit
  ),
  inserted_recipients as (
    insert into public.social_notification_rate_limit_events (
      event_type,
      actor_user_id,
      recipient_user_id,
      resource_id
    )
    select
      normalized_event_type,
      actor_user_id_input,
      eligible_recipients.recipient_id,
      nullif(btrim(coalesce(resource_id_input, '')), '')
    from eligible_recipients
    on conflict do nothing
    returning public.social_notification_rate_limit_events.recipient_user_id
  )
  select inserted_recipients.recipient_user_id
    from inserted_recipients;
end;
$$;

revoke all on public.social_notification_rate_limit_events from anon;
revoke all on public.social_notification_rate_limit_events from authenticated;
revoke all on function public.reserve_social_notification_delivery(text, uuid, uuid[], text) from public;
revoke all on function public.reserve_social_notification_delivery(text, uuid, uuid[], text) from anon;
revoke all on function public.reserve_social_notification_delivery(text, uuid, uuid[], text) from authenticated;
grant execute on function public.reserve_social_notification_delivery(text, uuid, uuid[], text) to service_role;

comment on table public.social_notification_rate_limit_events
  is 'Server-owned push throttle ledger; client roles have no direct access.';

comment on function public.reserve_social_notification_delivery(text, uuid, uuid[], text)
  is 'Service-role RPC that atomically reserves social push recipients after cooldown and volume checks.';

commit;
